/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_apicode_jbasedconsole_platform_LinuxConsoleImpl */

#ifndef _Included_net_apicode_jbasedconsole_platform_LinuxConsoleImpl
#define _Included_net_apicode_jbasedconsole_platform_LinuxConsoleImpl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_apicode_jbasedconsole_platform_LinuxConsoleImpl
 * Method:    beep
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_net_apicode_jbasedconsole_platform_LinuxConsoleImpl_beep
  (JNIEnv *, jobject);

/*
 * Class:     net_apicode_jbasedconsole_platform_LinuxConsoleImpl
 * Method:    getSize0
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_net_apicode_jbasedconsole_platform_LinuxConsoleImpl_getSize0
  (JNIEnv *, jobject);

/*
 * Class:     net_apicode_jbasedconsole_platform_LinuxConsoleImpl
 * Method:    readCharacter0
 * Signature: ()C
 */
JNIEXPORT jchar JNICALL Java_net_apicode_jbasedconsole_platform_LinuxConsoleImpl_readCharacter0
  (JNIEnv *, jobject);

/*
 * Class:     net_apicode_jbasedconsole_platform_LinuxConsoleImpl
 * Method:    resetInputBuffer0
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_net_apicode_jbasedconsole_platform_LinuxConsoleImpl_resetInputBuffer0
  (JNIEnv *, jobject);

/*
 * Class:     net_apicode_jbasedconsole_platform_LinuxConsoleImpl
 * Method:    setTitle0
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_net_apicode_jbasedconsole_platform_LinuxConsoleImpl_setTitle0
  (JNIEnv *, jobject, jstring);

/*
 * Class:     net_apicode_jbasedconsole_platform_LinuxConsoleImpl
 * Method:    setCursorVisible0
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_net_apicode_jbasedconsole_platform_LinuxConsoleImpl_setCursorVisible0
  (JNIEnv *, jobject, jboolean);

#ifdef __cplusplus
}
#endif
#endif
